INSERT INTO `Content` (`id`, `updated`, `type`, `title`, `description`, `keywords`, `url`, `section`, `content`, `sitemap`) VALUES
(1, '0000-00-00 00:00:00', 'Home Page', 'Home Page', '', '', '', 'general', '', 0),
(2, '0000-00-00 00:00:00', 'Home Page Bottom', 'Home Page Bottom', '', '', '', 'general', '', 0),
(3, '0000-00-00 00:00:00', 'Directory Results', 'Directory Results', '', '', '', 'general', '', 0),
(4, '0000-00-00 00:00:00', 'Directory Results Bottom', 'Directory Results Bottom', '', '', '', 'general', '', 0),
(5, '0000-00-00 00:00:00', 'Advertise with Us', 'Advertise with Us', '', '', '', 'advertise_general', '<h1>Sign up today - It''s quick and simple!</h1>\r\n<br />\r\n<p>Demo Directory is proud to announce its new directory service which is now available online to visitors and new suppliers. It boasts endless amounts of new features for customers and suppliers.</p>\r\n<p>Your directory items are also controlled entirely by you. We have a members interface where you can log in and change any details, add special promotions for Demo Directory customers and much more!</p><br />', 0),
(6, '0000-00-00 00:00:00', 'Advertise with Us Bottom', 'Advertise with Us Bottom', '', '', '', 'advertise_general', '', 0),
(7, '0000-00-00 00:00:00', 'Contact Us', 'Contact Us', '', '', '', 'general', '<h4>Contact Us</h4><hr />', 0),
(8, '0000-00-00 00:00:00', 'Terms of Use', 'Terms of Use', 'Terms of Use', '', '', 'general', '<h2>Terms of Use</h2>\r\n<p>&nbsp;</p>\r\n<p>Pellentesque nulla sem, suscipit quis mattis et, imperdiet nec massa. Mauris faucibus fermentum aliquam. Aliquam commodo egestas iaculis. Pellentesque ut mauris nisi, commodo gravida elit. Phasellus eget diam eros. Donec ante velit, dignissim in congue eget, congue in quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ut ipsum nisi, ut pulvinar augue. Quisque blandit facilisis velit non ornare. Cras et urna nunc. Praesent non ante urna. Sed vehicula nulla sit amet lacus mattis scelerisque. Sed non felis arcu. Morbi congue aliquet ante, quis vestibulum ipsum gravida non. Sed ante felis, lobortis ac pharetra fermentum, aliquet id elit.<br /><br />Maecenas lobortis eleifend turpis, eu luctus sapien ultricies vitae. Aliquam erat volutpat. Nullam dolor odio, dapibus sed pellentesque nec, adipiscing eget quam. Integer mi sem, pharetra ac convallis eget, sodales in mauris. Suspendisse quis urna non nisl ullamcorper imperdiet a quis eros. Vivamus egestas posuere consequat. Nulla a commodo nunc. Morbi ut enim lectus, vitae pretium dui. Phasellus lacinia, lorem id malesuada luctus, enim augue fermentum augue, eu luctus dolor magna et turpis. Praesent vitae ornare mauris.<br /><br />Nam eget libero at tortor auctor placerat at vitae orci. Fusce tempus luctus dolor. Vivamus pharetra erat vitae ipsum pharetra ut tincidunt lacus pharetra. Sed viverra interdum fringilla. Aenean cursus nulla at neque luctus et pellentesque ante dignissim. Ut luctus odio et velit suscipit imperdiet. Cras semper, leo quis venenatis elementum, nibh diam blandit nulla, ut dictum ipsum lectus non diam. Vivamus ac convallis velit. Nulla est magna, bibendum eu luctus sed, dignissim in libero. Etiam sit amet purus ut odio mollis varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non velit vel augue mollis blandit eu eu metus. Morbi dapibus porttitor scelerisque. Praesent ultricies erat ac nisi laoreet sit amet consequat leo fringilla. Fusce egestas neque ut nisl mattis eget dignissim elit accumsan. Phasellus mollis dapibus tristique. Sed ut velit non nibh sagittis ornare sed feugiat nibh.<br />?</p>', 0),
(9, '0000-00-00 00:00:00', 'Listing Advertisement', 'Listing Advertisement', '', '', '', 'advertise_listing', '', 0),
(10, '0000-00-00 00:00:00', 'Listing Home', 'Listing Home', '', '', '', 'listing', '', 0),
(11, '0000-00-00 00:00:00', 'Listing Home Bottom', 'Listing Home Bottom', '', '', '', 'listing', '', 0),
(12, '0000-00-00 00:00:00', 'Listing Results', 'Listing Results', '', '', '', 'listing', '', 0),
(13, '0000-00-00 00:00:00', 'Listing Results Bottom', 'Listing Results Bottom', '', '', '', 'listing', '', 0),
(14, '0000-00-00 00:00:00', 'Listing View All Categories', 'Listing View All Categories', '', '', '', 'listing', '', 0),
(15, '0000-00-00 00:00:00', 'Listing View All Categories Bottom', 'Listing View All Categories Bottom', '', '', '', 'listing', '', 0),
(16, '0000-00-00 00:00:00', 'Listing View All Locations', 'Listing View All Locations', '', '', '', 'listing', '', 0),
(17, '0000-00-00 00:00:00', 'Listing View All Locations Bottom', 'Listing View All Locations Bottom', '', '', '', 'listing', '', 0),
(18, '0000-00-00 00:00:00', 'Deal Home', 'Deal Home', '', '', '', 'deal', '', 0),
(19, '0000-00-00 00:00:00', 'Deal Home Bottom', 'Deal Home Bottom', '', '', '', 'deal', '', 0),
(20, '0000-00-00 00:00:00', 'Deal Results', 'Deal Results', '', '', '', 'deal', '', 0),
(21, '0000-00-00 00:00:00', 'Deal Results Bottom', 'Deal Results Bottom', '', '', '', 'deal', '', 0),
(22, '0000-00-00 00:00:00', 'Deal View All Categories', 'Deal View All Categories', '', '', '', 'deal', '', 0),
(23, '0000-00-00 00:00:00', 'Deal View All Categories Bottom', 'Deal View All Categories Bottom', '', '', '', 'deal', '', 0),
(24, '0000-00-00 00:00:00', 'Deal View All Locations', 'Deal View All Locations', '', '', '', 'deal', '', 0),
(25, '0000-00-00 00:00:00', 'Deal View All Locations Bottom', 'Deal View All Locations Bottom', '', '', '', 'deal', '', 0),
(26, '0000-00-00 00:00:00', 'Event Advertisement', 'Event Advertisement', '', '', '', 'advertise_event', '', 0),
(27, '0000-00-00 00:00:00', 'Event Home', 'Event Home', '', '', '', 'event', '', 0),
(28, '0000-00-00 00:00:00', 'Event Home Bottom', 'Event Home Bottom', '', '', '', 'event', '', 0),
(29, '0000-00-00 00:00:00', 'Event Results', 'Event Results', '', '', '', 'event', '', 0),
(30, '0000-00-00 00:00:00', 'Event Results Bottom', 'Event Results Bottom', '', '', '', 'event', '', 0),
(31, '0000-00-00 00:00:00', 'Event View All Categories', 'Event View All Categories', '', '', '', 'event', '', 0),
(32, '0000-00-00 00:00:00', 'Event View All Categories Bottom', 'Event View All Categories Bottom', '', '', '', 'event', '', 0),
(33, '0000-00-00 00:00:00', 'Event View All Locations', 'Event View All Locations', '', '', '', 'event', '', 0),
(34, '0000-00-00 00:00:00', 'Event View All Locations Bottom', 'Event View All Locations Bottom', '', '', '', 'event', '', 0),
(35, '0000-00-00 00:00:00', 'Banner Advertisement', 'Banner Advertisement', '', '', '', 'advertise_banner', '<h2>Banners</h2><br /><table><tr><td class="advertiseScreen"><ul><li>Display targeted ads that match the directory content </li><li>Reach people seeking information on products and services in the directory </li><li>Build brand recognition </li><li>Return on Investment - Start getting customers in minutes!</li></ul></td></tr></table>', 0),
(36, '0000-00-00 00:00:00', 'Classified Advertisement', 'Classified Advertisement', '', '', '', 'advertise_classified', '', 0),
(37, '0000-00-00 00:00:00', 'Classified Home', 'Classified Home', '', '', '', 'classified', '', 0),
(38, '0000-00-00 00:00:00', 'Classified Home Bottom', 'Classified Home Bottom', '', '', '', 'classified', '', 0),
(39, '0000-00-00 00:00:00', 'Classified Results', 'Classified Results', '', '', '', 'classified', '', 0),
(40, '0000-00-00 00:00:00', 'Classified Results Bottom', 'Classified Results Bottom', '', '', '', 'classified', '', 0),
(41, '0000-00-00 00:00:00', 'Classified View All Categories', 'Classified View All Categories', '', '', '', 'classified', '', 0),
(42, '0000-00-00 00:00:00', 'Classified View All Categories Bottom', 'Classified View All Categories Bottom', '', '', '', 'classified', '', 0),
(43, '0000-00-00 00:00:00', 'Classified View All Locations', 'Classified View All Locations', '', '', '', 'classified', '', 0),
(44, '0000-00-00 00:00:00', 'Classified View All Locations Bottom', 'Classified View All Locations Bottom', '', '', '', 'classified', '', 0),
(45, '0000-00-00 00:00:00', 'Article Advertisement', 'Article Advertisement', '', '', '', 'advertise_article', '<table><tr>\r\n<td class="advertiseScreen">Post your article and become known to prospective clients and customers.\r\n</td>\r\n</tr></table>', 0),
(46, '0000-00-00 00:00:00', 'Article Home', 'Article Home', '', '', '', 'article', '', 0),
(47, '0000-00-00 00:00:00', 'Article Home Bottom', 'Article Home Bottom', '', '', '', 'article', '', 0),
(48, '0000-00-00 00:00:00', 'Article Results', 'Article Results', '', '', '', 'article', '', 0),
(49, '0000-00-00 00:00:00', 'Article Results Bottom', 'Article Results Bottom', '', '', '', 'article', '', 0),
(50, '0000-00-00 00:00:00', 'Article View All Categories', 'Article View All Categories', '', '', '', 'article', '', 0),
(51, '0000-00-00 00:00:00', 'Article View All Categories Bottom', 'Article View All Categories Bottom', '', '', '', 'article', '', 0),
(52, '0000-00-00 00:00:00', 'Sponsor Home', 'Sponsor Home', '', '', '', 'member', '', 0),
(53, '0000-00-00 00:00:00', 'Sponsor Home Bottom', 'Sponsor Home Bottom', '', '', '', 'member', '', 0),
(54, '0000-00-00 00:00:00', 'Manage Account', 'Manage Account', '', '', '', 'member', '', 0),
(55, '0000-00-00 00:00:00', 'Manage Account Bottom', 'Manage Account Bottom', '', '', '', 'member', '', 0),
(56, '0000-00-00 00:00:00', 'Sponsor Help', 'Sponsor Help', '', '', '', 'member', '', 0),
(57, '0000-00-00 00:00:00', 'Sponsor Help Bottom', 'Sponsor Help Bottom', '', '', '', 'member', '', 0),
(58, '0000-00-00 00:00:00', 'Transaction', 'Transaction', '', '', '', 'member', '', 0),
(59, '0000-00-00 00:00:00', 'Transaction Bottom', 'Transaction Bottom', '', '', '', 'member', '', 0),
(60, '0000-00-00 00:00:00', 'Sitemap', 'Sitemap', '', '', '', 'general', '', 0),
(61, '0000-00-00 00:00:00', 'Error Page', 'Error Page', 'Page not found', '', '', 'general', '<table style="width: 100%;" border="0" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td style="text-align: center; background-color: #eaf4fb; height: 175px;" align="center" valign="middle"><span style="color: #3498db;"><strong><span style="font-size: x-large;">It appears something in the machine has broken</span></strong></span></td></tr><tr><td>&nbsp;<table style="width: 100%;" border="0" cellpadding="5"><tbody><tr><td style="width: 50%;" align="center" valign="middle">&nbsp;</td><td align="center" valign="middle"><p style="text-align: left;"><span style="color: #3498db;"><strong><span style="font-size: large;">Did you destroy something?</span></strong></span></p><p style="text-align: left;"><span style="color: #3498db;"><strong><span style="font-size: large;"><br /></span></strong></span></p><p style="text-align: left;"><span style="font-size: small;">Of course not, just a simple error on our part, perhaps you visited a bad URL or typed something incorrectly. No problems, these things happen, the important thing is we&rsquo;re still here and so are you.</span></p><p style="text-align: left;"><span style="font-size: medium;"><br /></span></p><p style="text-align: left;"><span style="font-size: medium;"><br /></span></p><p style="text-align: left;"><strong><span style="font-size: large; color: #3498db;">What to do about this pickle...</span></strong></p><p style="text-align: left;"><strong><span style="font-size: large; color: #3498db;"><br /></span></strong></p><ol><li style="text-align: left;"><span style="font-size: small;">Try using the search at at the top there.</span></li><li style="text-align: left;"><span style="font-size: small;">Try using the navigation at the top as well.</span></li><li style="text-align: left;"><span style="font-size: small;">Sure, there&rsquo;s a problem - Contact Us (We&rsquo;ll fix it)</span></li></ol><p style="text-align: left;"><span style="font-size: x-large;"><br /></span></p><p style="text-align: left;"><span style="font-size: medium;"><br /></span></p><p style="text-align: left;"><span style="font-size: medium;"><br /></span></p><p>&nbsp;</p></td></tr></tbody></table></td></tr></tbody></table>', 0),
(62, '0000-00-00 00:00:00', 'Maintenance Page', 'Maintenance Page', '', '', '', 'general', '<table id="maintenancemode" style="width: 100%;" border="0" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td id="bg-maintenancemode" style="text-align: center; height: 245px;" align="center" valign="middle">&nbsp;</td></tr><tr><td style="text-align: center; background-color: #eaf4fb; height: 175px;" align="center" valign="middle"><span style="color: #3498db;"><strong><span style="font-size: x-large;">Whoa there Cowboy... This Website is currently down for maintenance, back soon. </span></strong></span></td></tr><tr><td>&nbsp;<p style="text-align: center;"><span style="font-size: small;">We&rsquo;ll be down for a brief period while we make some changes.</span></p><p style="text-align: center;"><span style="font-size: small;">Please, come back later for more information.</span></p><div style="text-align: center;"><span><br /></span></div></td></tr></tbody></table>', 0),
(63, '0000-00-00 00:00:00', 'Profile Page', 'Profile Page', '', '', '', 'general', '', 0),
(64, '0000-00-00 00:00:00', 'Profile Page Bottom', 'Profile Page Bottom', '', '', '', 'general', '', 0),
(65, '0000-00-00 00:00:00', 'Add Profile Page', 'Add Profile Page', '', '', '', 'general', '', 0),
(66, '0000-00-00 00:00:00', 'Packages Offer', 'Packages Offer', '', '', '', 'advertise_general', '', 0),
(67, '0000-00-00 00:00:00', 'Blog Home', 'Blog Home', '', '', '', 'blog', '', 0),
(68, '0000-00-00 00:00:00', 'Blog Home Bottom', 'Blog Home Bottom', '', '', '', 'blog', '', 0),
(69, '0000-00-00 00:00:00', 'Blog Results', 'Blog Results', '', '', '', 'blog', '', 0),
(70, '0000-00-00 00:00:00', 'Blog Results Bottom', 'Blog Results Bottom', '', '', '', 'blog', '', 0),
(71, '0000-00-00 00:00:00', 'Blog View All Categories', 'Blog View All Categories', '', '', '', 'blog', '', 0),
(72, '0000-00-00 00:00:00', 'Blog View All Categories Bottom', 'Blog View All Categories Bottom', '', '', '', 'blog', '', 0),
(73, '0000-00-00 00:00:00', 'Best Of', 'Best Of', '', '', '', 'general', '', '0'),
(74, '0000-00-00 00:00:00', 'Leads Form', 'Enquire', '', '', '', 'general', '<h1>Did you not find what you''re looking for?</h1><p>Please, let us know more about what you''re looking for.&nbsp;<span>We''d like to know a few details so we can present you with the best options available.</span></p>', '0'),
(75, '0000-00-00 00:00:00', 'Listing Change Level', 'Listing Change Level', '', '', '', 'member', '', 0),
(76, '0000-00-00 00:00:00', 'Event Change Level', 'Event Change Level', '', '', '', 'member', '', 0),
(77, '0000-00-00 00:00:00', 'Classified Change Level', 'Classified Change Level', '', '', '', 'member', '', 0);